### ISSUE TITLE
--convert `WARNING: Ignored surplus positional argument ` error

### ISSUE THREAD

**Issue by daviddever** [robhagemans/pcbasic#113]
## Bug report

**Problem**
Error when using `--convert` 
``WARNING: Ignored surplus positional argument `TEST.BAS` `` then sits at cursor on new line

**Steps**
1.  Run `pcbasic --convert=A TEST.BAS TESTA.BAS`

**Program**

Simple test program to be sure it wasn't something weird with the program being exported

```
10 PRINT "HELLO WORLD"
20 END
```

**Notes**

PC-BASIC version:  2.0.2
Operating system version:  Ubuntu 20.04
Python: 3.8.2 
Installed with pip

`--convert=A|B|P` produces the same behavior.

I verified that `--load` for the same file works. I also tested with an old program and one saved in PC-Basic. Testing with a non existent file produces the same results

Thanks this is an awesome project!

**Comment by daviddever** [comment]
Forgot PC-Basic version

**Comment by robhagemans** [comment]
Haven't reproduced yet, but looks like a bug. Possibly due to some change that happened between Python 2.7 and 2.8. Will need to try with 2.8.

**Comment by robhagemans** [comment]
Actually, the issue is that pcbasic doesn't currently accept positional arguments after flags, so the command needs to be entered this way:

    pcbasic TEST.BAS TESTA.BAS --convert=A

I realise this is confusing as most command-line tools do accept and even prefer flags before positional arguments. There's some difficulty getting this to work consistently given the need to avoid ambiguity if people do `--convert A`, which is also allowed. The answer may be simply to require the `=`.

**Comment by daviddever** [comment]
Thanks!

Might be worth updating the documentation at  http://robhagemans.github.io/pcbasic/doc/2.0/#programs where the example is with the flag first.

**Comment by robhagemans** [comment]
I've made some changes in command-line handling to make this more intuitive.
