### ISSUE TITLE
[v1.2 only] Crash when codepage is set to sp65001

### ISSUE THREAD

**Issue by AbdelrahmanAhmedh** [robhagemans/pcbasic#138]
## Bug report 
![cp65001](https://user-images.githubusercontent.com/86836980/124276821-980a4100-db44-11eb-8084-4816da8c0bd6.png)

**Problem**

**Notes**

PC-BASIC version: 1.2.14 
Operating system version: windows 10 x64 20h2 

<!-- pc basic program was working well in windows 7

**Comment by Marrin** [comment]
AFAIK That's pretty much an ”error” in Python 2.7 which won't be fixed there because 2.7 isn't maintained any more.

So I would suggest using PC-BASIC 2.x instead, which runs on currently maintained Python 3.x versions which know about code page 65001 on windows systems.

@robhagemans Do you still support Python 2 after its end of life passed well over a year ago now?

**Comment by robhagemans** [comment]
@Marrin is correct, unicode support on Windows in Python 2.7 is essentially broken and this issue can't be fixed. Workarounds are either use the current 2.x branch built on Python 3, or to set your codepage to something else than cp65001. 

PC-BASIC 1.x probably wont see any further updates - I might do a "final" release marking it as legacy. It is quite stable apart from rare issues like with cp65001 - which is not commonly used because the Windows codepage itself is also semi-broken and not fully compliant with utf-8... However 1.x unmaintainable as the code is a total mess of quick fixes and Python 2.7 is end-of-life. Further development (if and when) will only be on 2.x with Python 3 support only.

**Comment by robhagemans** [comment]
Included a workaround in commit 070cd63d. Untested, but still.
