### ISSUE TITLE
once-working 2.0.4 release now fails to launch on macOS 12.x

### ISSUE THREAD

**Issue by incanus** [robhagemans/pcbasic#203]
Separate from https://github.com/robhagemans/pcbasic/issues/131, even the once-built-properly last release, 2.0.4, fails to launch on macOS 12.5. The relevant crash log snippet is: 

```
Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: '@executable_path/lib/Python'
Referenced from: '/private/var/folders/*/PC-BASIC-2.0.app/Contents/MacOS/pcbasic'
Reason: tried: '' (code signature invalid (errno=1) sliceOffset=0x00000000, codeBlobOffset=0x003104A0, codeBlobSize=0x0000EB10 for ''), '' (no such file), '' (no such file)
(terminated at launch; ignore backtrace)
```

This is probably related to the [mid-major-release removal of Python 2](https://developer.apple.com/documentation/macos-release-notes/macos-12_3-release-notes#Python) as of macOS 12.3 (March 2022). 

@robhagemans Can I suggest a new label for `build`-related issues?

**Comment by robhagemans** [comment]
Thanks guys! Label for build issues is a good idea, might even have
separate ones per platform.

I intend to add some write up on the packaging process in BUILD.md, but
meanwhile the gist is: you need a clone of the repo and all the
prerequisites in BUILD.md. The packaging process uses cx-Freeze at the
core, in principle it's a matter of running python3 -m packaging from the
repo root and all goes automatically.

The package contains a full python distribution so should not depend on
what is installed on the Mac. However, the issues you point out may be
caused by libraries python depends on which may have been removed. I
thought 2.0.4 package used Python3 not Python2 however, but maybe I got
that wrong.

**Comment by robhagemans** [comment]
Sorry my previous message was in response to both this and #131, so probably a bit confusing, but key points are there.

In any case, for both issues, help from the Mac community much appreciated! I've reached the limits of my ability/understanding of MacOS and relying on a virtual hackintosh doesn't seem to produce workable builds anymore.

**Comment by robhagemans** [comment]
By the way, while this is useful information,  I think if anything we should get 2.0.5 working and leave 2.0.4 be. If Apple retroactively broke packages, people should just upgrade to the latest version.

**Comment by incanus** [comment]
Agree; closing now in favor of work elsewhere.
