### ISSUE TITLE
USAGE.txt  missing

### ISSUE THREAD

**Issue by nganfei** [robhagemans/pcbasic#209]
## Bug report

Just one file missing

**Problem**

**Steps**

**Program**

**Crash log**

**Notes**

PC-BASIC version:  
Operating system version:

**Comment by robhagemans** [comment]
How did you install PC-BASIC? 

I'm asking because this is what happens if you simply clone the repository and try to run. As explained in `BUILD.md` in that case you need to run `python3.7 -m make local`. This creates local files including `USAGE.txt`. 

The recommended way to install PC-BASIC is through `pip` or one of the release packages where this file is included.

**Comment by nganfei** [comment]
just pip install pcbasic

**Comment by robhagemans** [comment]
Thanks, I found the issue in the pip packages. I've uploaded a fixed package to pypi (2.0.6.post2), please upgrade.

**Comment by robhagemans** [comment]
This would only occur if you've cloned the repo and use it right there. You
need to either install from a package, or use the make scripts to create
documentation including USAGE txt.
