### ISSUE TITLE
error when try acess port com1

### ISSUE THREAD

**Issue by imartynetz** [robhagemans/pcbasic#3]
I have a basica code who already run ok on ms-dos, but im trying to make it running on windows, and using pc-basic i put on pcbasic.ini the following line

`com1=PORT:COM2`

and my port com2 its a serial usb, i load the program and when i run i got 
![bug_pcbasic](https://cloud.githubusercontent.com/assets/9934980/14685058/36dd2376-0709-11e6-88be-acfef33fe40e.jpg)

**Comment by robhagemans** [comment]
Hi, thanks for the bug report!

It looks like we're trying to send a break signal to a COM port without having opened it. Clearly that should not result in a crash like this, however I'm not quite sure what the correct behaviour is (in other words, what GW-BASIC/BASICA does in this case).

If possible, could you send me the BASIC program you're running? It would help me debug this issue. Also could you let me know what sort of serial device the program is designed to operate?

Thanks
Rob

**Comment by imartynetz** [comment]
Hi,

I´m using a serial-usb who is the com2 port in my computer. The BASIC program run correct on ms-dos and on dos box (but could not make ctrl+break work on dos box).


this is the code.
[http://pastebin.com/SSSiLiFK](url)

**Comment by robhagemans** [comment]
Hi, thanks for the update! I will have a look at the code to understand what might be the expected outcome. 

Just a quick tip: Ctrl+Break does indeed not work on DOSBox, but if you have a Scroll-Lock key you can substitute with Ctrl+Scroll Lock which should do the same and I think works correctly.

**Comment by imartynetz** [comment]
I try ctrl+scroll and doesn´t work too, don´t know why. I got dosbox svn daum who already have the ctrl+break patch and dont work either. I don´t try on other computer.

**Comment by imartynetz** [comment]
Hi, i trying using dosbox on other computer, and either ctrl+break or ctrl+scroll lock doesn´t work, and accidentally i press ctrl+Num lock... and break. Well now its working perfect.

**Comment by robhagemans** [comment]
Hi great that dosbox works for you now! I had alook at the code - it's interesting, the program controls the `COM1` port exclusively through `OUT` and `INP` rather than through `OPEN "COM1:"`. I imagine the connection should be set up with default serial parameters in this case to avoid the crash - will implement this for the .8 release of PC-BASIC so that we can try if that makes it work. 

It's always a bit difficult debugging issues with serial communications since there are so many components involved that can behave unexpectedly - PC-BASIC itself of course, but also the program, the USB serial port emulator as well as the serial device  to which I have no access...

**Comment by robhagemans** [comment]
This should be fixed by commits 5e8e019 and b224bff which will be included in the .8 release. I'm expecting to release that this weekend. Would you be able to check if this fixes the issue on your setup?

Apologies for the delay in this - I haven't been able to put much time into this recently. I expect it to be a bit easier in the next few weeks, so if more serial communication bugs show up I hope ti be able to solve them more quickly.

**Comment by robhagemans** [comment]
Closing this - if the problem persists in the new version please feel free to reopen or to open a new ticket.
