### ISSUE TITLE
Exception when trying to list files on Cassette Tape 

### ISSUE THREAD

**Issue by joshuashaffer** [robhagemans/pcbasic#4]
![selection_166](https://cloud.githubusercontent.com/assets/5630735/14864408/c604e312-0c87-11e6-9018-86e0390cbd15.png)

./pcbasic.py --cas1=WAV:IBM_PC_Diagnostics_Cassette.wav --current-device=CAS1

Then, tried to list files with "files". Wave was converted from http://www.brutman.com/Cassette_Waveforms/IBM_PC_Diagnostics_Cassette.mp3

**Comment by robhagemans** [comment]
Hi, thanks for the report and for the extra information! I know where the problem lies and I will fix the crash.

Note though that even when the bug that causes the crash is fixed this will not do what you expect: `FILES` is a disk-only command and will give an error message when attempted on the `CAS1:` device (though it shouldn't crash like this of course).

To get the contents of a cassette image, you can use a trick: try to `LOAD` a file name that you know is not present on the cassette and it will list all file names on the tape as `Skipped`. For example,
   
    LOAD "CAS1:@"

If you just want to load the first program on the tape, simply type `LOAD "CAS1:"`.

Note that the program on that IBM tape is mostly machine code, and machine code will not run on PC-BASIC. You should be able to `LOAD` and `LIST` the file without problems though.

Rob

**Comment by joshuashaffer** [comment]
Thanks!

**Comment by robhagemans** [comment]
Fixed by commits 94c8193 and f267e36
