### ISSUE TITLE
Playing bach.bas immediately crashes PC-BASIC 

### ISSUE THREAD

**Issue by hexbus** [robhagemans/pcbasic#92]
Using latest PC build 1.2.14.

Upon loading and running this file (after unzipping):  ftp://ftp.oldskool.org/pub/tvdog/tandy1000/basic/bach.zip

PC-BASIC immediately quits.

Running latest version of Windows 10 on a Thinkpad 25 laptop.    Only change I made was "preset=tandy" in the config file.  Tried another Tandy specific file to verify the preset was set correctly (ftp://ftp.oldskool.org/pub/tvdog/tandy1000/basic/baghdad.zip) and this ran fine.

**Comment by robhagemans** [comment]
Hi, thanks for reporting this!

Unfortunately I can't reproduce the problem - this (Bach Trio Sonata No 1 in E flat) runs fine on PC-BASIC 1.2.14 on my (virtualbox) install of Windows 10. 

However, there have been a number of similar reports of crashes of sound programs on 64-bit Windows that I'm also unable to reproduce on my setup; I think the problem arises in the PyGame library depending on some version of some Windows DLL or other, but since I can't generate the crash myself I can't be sure. I've spent considerable time with another reporter previously to dig into this, but to no avail.

Have you tried running this on PC-BASIC 2.0.1? This uses SDL2 instead of PyGame and may not have the issue... let me know either way.

**Comment by hexbus** [comment]
Thanks for the quick response!  I have 2.0.1 loaded, but will need to try and figure out where to put the bach.bas file.  When I put it in C:\users\myname\bach.bas - 2.0.1 can't find it.  I also can't save in 2.0.1 either, so that tells me it's using a different directory. :)
