### ISSUE TITLE
DRAW scaling buggy?

### ISSUE THREAD

**Issue by dilbertino** [robhagemans/pcbasic#93]
## Bug report
**Problem**
scaling in DRAW statement seems buggy

**Steps**
DRAW "bm100,100s4f19g19h19e19"
This draws a closed diamond shape.
Now when the scale is changed to any non-multiple of 4, the shape is no longer closed:
DRAW "bm100,100s5f19g19h19e19"
The funny thing is that the "gap" in the diamond seems to be the same size, no matter what the scale is (as long as it's not a multiple of 4).
Directions "f" and "h" seem to scale OK, but direction "e" and "g" seem off/drifting by 1 pixel (the line is jagged in the middle).
This happens in any graphics mode (screen 1,2,9). I noticed this because some of my old .BAS programs used DRAW with flash fill but the shapes were no longer closed so the result was a paint mess : )
 
PC-BASIC version:  1.2.14
Operating system version:  Win7

**Comment by robhagemans** [comment]
Ha! Thanks for reporting. That's a bug indeed, and the reason is that Python's `//` rounds towards negative infinity whereas C's integer division rounds towards zero, and I didn't know that when I wrote this code :)

Will fix, at least in the 2.0 branch - I'm not sure at this stage whether I will do another release on the 1.2 branch but if I do I'll include this as well.

**Comment by robhagemans** [comment]
Fixed by commits c163d71, 64739eb
