### ISSUE TITLE
Can't OPEN accept a string expression as filename?

### ISSUE THREAD

**Issue by udhos** [robhagemans/pcbasic#95]
I do not claim this is bug, since it might be a sad GW-BASIC limitation.

The program below yields `Bad file number in 140`

How can that limitation be circumvented to open a user-supplied filename?

```
100 c$=environ$("CAT")
110 print "will output contents of text file CAT=";c$
120 if len(c$)<1 then print "please set the env var CAT": end
130 print "output:"
140 open c$ for input as 1
150 while not eof(1)
160 input #1, line$
170 print line$
180 count=count+1
190 wend
200 print count;" lines"
```

**Comment by robhagemans** [comment]
Hi, thanks for reporting!

For me the above program works OK (note that lines `160` and `170` need to be modified for it to run; `LINE$` is not a valid variable name because `LINE` is a keyword).

What are the contents of your environment variable `CAT` and hence of `C$` ? The error you report would be caused if, for example, `C$` is empty or contains forward slashes or other illegal characters in DOS filenames.

**Comment by udhos** [comment]
Hi, thanks for the clarification. You have spotted perfectly the issue: I was trying to put forward slashes in c$. Sorry for the noise!
