### ISSUE TITLE
Issue "loading" the file

### ISSUE THREAD

**Issue by AirGar** [robhagemans/pcbasic#99]
## Bug report

**Problem**

Program crashes when trying to open file 

**Steps**

1.  put HPREF.Bas in c:\users\gary\
2.  set to use pcbasic as default program to open HPREF.bas (see file change to be a pcbasic type file
3.  double click on HPREF.bas
4. I see quick flash of pcbasic black background then it disappears. 

**Program**

1. Get error "we do not support that type of file." when try to paste .BAS file. 
2. renamed to .TXT in Notepad to get into the GITHUB

[HPERF.txt](https://github.com/robhagemans/pcbasic/files/3146137/HPERF.txt)

**Crash log**

1. No log?

**Notes**

PC-BASIC version:  1.2
Operating system version:  W10 - latest

**Comment by robhagemans** [comment]
Hi, thanks! This is not a GW-BASIC file - it looks like QBASIC. GW-BASIC programs must have line numbers. 

PC-BASIC can only load/run GW-BASIC files. What you see is not a crash, it is PC-BASIC exiting directly because you are asking it to load this file on startup, and it's not a supported file type. This is expected behaviour, it's in line with how GW-BASIC works.

To run this program you'd need a different BASIC interpreter or compiler, you could try FreeBASIC or QB64.

**Comment by AirGar** [comment]
Got it… thanks. Someone gave me this and just said “it’s a basic program”…

Gary

[Gary Investments]
